
POST http://localhost:8000/api/v1/books/ HTTP/1.1
Content-Type: application/json

{
    "title":  "Clean Code",
    "author": "Robert Martin",
    "year": 2022,
    "count_pages": 500,
    "seller_id": 5
}

###

POST http://localhost:8000/api/v1/books/ HTTP/1.1
Content-Type: application/json

{
    "title":  "War and Peace",
    "author": "Lev Tolstoy",
    "year": 2030,
    "count_pages": 1500,
    "seller_id": 5
}

###

POST http://localhost:8000/api/v1/books/ HTTP/1.1
Content-Type: application/json

{
    "title":  "How to sing if bear stepped on your ear",
    "author": "Buzova Olga",
    "year": 2022,
    "count_pages": 7,
    "seller_id": 4
}

###
GET http://localhost:8000/api/v1/books/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/api/v1/books/1 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:8000/api/v1/books/1 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/api/v1/books/2 HTTP/1.1
Content-Type: application/json

{
    "id": 7,
    "title": "Clean Architecture",
    "author": "Robert Martin",
    "year": 2025,
    "pages": 315,
    "seller_id": 2
}

###

POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "Alexey",
    "last_name": "Petrov",
    "email": "ap@mail.com",
    "password": "a12347823!"
}
###

POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "Kolka",
    "last_name": "Puzov",
    "email": "kolyan_nadmenniy@mail.com",
    "password": "sdfyu3hfi&"
}

###

POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "Kolka",
    "last_name": "Puzov",
    "email": "kolyan_nadmenniy@mail.com",
    "password": "sdfyu3hfi"
}

###

POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
Content-Type: application/json

{
    "first_name": "Olga",
    "last_name": "Buzova",
    "email": "best_singer@mail.com",
    "password": "malo_poloviN!"
}

###

GET http://localhost:8000/api/v1/sellers/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/api/v1/sellers/2 HTTP/1.1
Content-Type: application/json

###
DELETE http://localhost:8000/api/v1/sellers/1 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/api/v1/sellers/4 HTTP/1.1
Content-Type: application/json

{
    "id": 100,
    "first_name": "Vasya",
    "last_name": "Trusikov",
    "email": "vasya_velikiy@mail.com"
}
